config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :shops
  resources :products
  resources :users
  resources :advertisments

end

app/models/advertisment.rb
class Advertisment < ActiveRecord::Base

  belongs_to :user

  validates :title, presence: true
  validates :description, length: {minimum: 10}


  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

end

app/controllers/advertisments_controller.rb
class AdvertismentsController < ApplicationController
  before_action :set_advertisment, only: [:show, :edit, :update, :destroy]

  # GET /advertisments
  # GET /advertisments.json
  def index
    @advertisments = Advertisment.all
  end

  # GET /advertisments/1
  # GET /advertisments/1.json
  def show
  end

  # GET /advertisments/new
  def new
    @advertisment = Advertisment.new
  end

  # GET /advertisments/1/edit
  def edit
  end

  # POST /advertisments
  # POST /advertisments.json
  def create
    @advertisment = Advertisment.new(advertisment_params)

    respond_to do |format|
      if @advertisment.save
        format.html { redirect_to @advertisment.user, notice: 'Advertisment was successfully created.' }
        format.json { render :show, status: :created, location: @advertisment }
      else
        format.html { render :new }
        format.json { render json: @advertisment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advertisments/1
  # PATCH/PUT /advertisments/1.json
  def update
    respond_to do |format|
      if @advertisment.update(advertisment_params)
        format.html { redirect_to @advertisment.user, notice: 'Advertisment was successfully updated.' }
        format.json { render :show, status: :ok, location: @advertisment }
      else
        format.html { render :edit }
        format.json { render json: @advertisment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertisments/1
  # DELETE /advertisments/1.json
  def destroy
    @advertisment.destroy
    respond_to do |format|
      format.html { redirect_to advertisments_url, notice: 'Advertisment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertisment
      @advertisment = Advertisment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertisment_params
      params.require(:advertisment).permit(:description, :title, :photo, :user_id)
    end
end

app/helpers/advertisments_helper.rb
module AdvertismentsHelper
end

app/views/advertisments/_form.html.erb
<h1>New Advertisment</h1>

<%= form_for(advertisment, html: { multipart: true }) do |f| %>
  <% if advertisment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advertisment.errors.count, "error") %> prohibited this advertisment from being saved:</h2>

      <ul>
      <% advertisment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.hidden_field :user_id %>
    </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.file_field :photo %>
  </div>
    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/advertisments/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Advertisments</h1>

<table>
  <thead>
  <tr>
    <th>Description</th>
    <th>Title</th>
    <th>User who published</th>
    <th>Photo</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% advertisments.each do |advertisment| %>
      <tr>
        <td><%= advertisment.description %></td>
        <td><%= advertisment.title %></td>
        <td><%= advertisment.user.username %></td>
        <td><%= image_tag advertisment.photo, width: 200, height: 200 %></td>
        <td><%= link_to 'Show', advertisment %></td>
        <td><%= link_to 'Edit', edit_advertisment_path(advertisment) %></td>
        <td><%= link_to 'Destroy', advertisment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/advertisments/edit.html.erb
<h1>Editing Advertisment</h1>

<%= render 'form' %>

<%= link_to 'Show', @advertisment %> |
<%= link_to 'Back', advertisments_path %>

app/views/advertisments/index.html.erb
<%= render 'index', advertisments: @advertisments %>

app/views/advertisments/new.html.erb
<%= render 'form', advertisment: @advertisment %>

<%= link_to 'Back', advertisments_path %>

app/views/advertisments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User who published:</strong>
  <%= @advertisment.user.username %>
</p>


<p>
  <strong>Description:</strong>
  <%= @advertisment.description %>
</p>

<p>
  <strong>Title:</strong>
  <%= @advertisment.title %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag @advertisment.photo, style: :medium %>
</p>

<%= link_to 'Edit', edit_advertisment_path(@advertisment) %> |
<%= link_to 'Back', advertisments_path %>